---
base_os:
  hostname: pella

main_trunk:
  interface: lagg0
  members:
    - hn2
    - hn3
  vlans:
    - name: servers0
      id: 2
      ip_address: 192.168.125.254/24
    - name: wired0
      id: 3
      ip_address: 172.16.3.254/24
    - name: wireless0
      id: 4
      ip_address: 172.16.4.254/24
    - name: wifikids0
      id: 41
      ip_address: 172.16.41.254/24
    - name: wifiguests0
      id: 42
      ip_address: 172.16.42.254/24
    - name: iot0
      id: 5
      ip_address: 172.16.5.254/24
    - name: cctv0
      id: 6
      ip_address: 172.16.6.254/24
    - name: mgmt0
      id: 9
      ip_address: 172.16.9.254/24
    - name: vms0
      id: 10
      ip_address: 172.16.10.254/24

internet:
  interface: hn0
  ip_address: DHCP
  ipv6_address: DHCP
