---
-
  hosts: all
  become: true
  become_method: doas
  roles:
    - role: base_os
      tags:
        - base_os

-
  hosts: routers
  become: true
  become_method: doas
  roles:
    - role: interfaces
      tags:
        - interfaces
    # - role: nat
    #   tags:
    #     - nat
