---
-
  hosts: all
  become: true
  become_method: doas
  roles:
    - role: base_os
      tags:
        - base_os

-
  hosts: routers
  become: true
  become_method: doas
  roles:
    - role: internet
      tags:
        - internet
    - role: nat
      tags:
        - nat
    - role: main_trunk
      tags:
        - main_trunk
