---
version: '3'
tasks:
  default:
    cmds:
      - task: run-ansible

  run-ansible:
    desc: Run Ansible playbook
    vars:
      ANSIBLE_TAGS: '{{.ANSIBLE_TAGS| default "all"}}'
      ANSIBLE_INVENTORY: '{{.ANSIBLE_INVENTORY| default "gns3"}}'
      ANSIBLE_USER_KEY: '{{.ANSIBLE_USER_KEY| default "$HOME/.ssh/id_rsa"}}'
    cmds:
      - |
        docker run --rm \
          -v $HOME/.ssh/known_hosts:/root/.ssh/known_hosts \
          -v {{.ANSIBLE_USER_KEY}}:/root/.ssh/ansible_key \
          -v $(pwd):/src \
          -w /src \
          alpine/ansible:latest \
          sh -c "chmod 600 /root/.ssh/ansible_key; ansible-playbook -i inventory/{{.ANSIBLE_INVENTORY}} main.yaml --tags {{.ANSIBLE_TAGS}}"
