---
- include_tasks: "tasks-pre.yaml"

- name: "Setup WAN interface"
  community.general.sysrc:
    name: "ifconfig_{{ internet.interface }}"
    value: "up"
  notify:
    - "restart network"

- name: "Bring up the aggregation interfaces"
  community.general.sysrc:
    name: "ifconfig_{{ item }}"
    value: "up"
  loop: "{{ main_trunk.members }}"
  notify:
    - "restart network"

- name: "Configure link aggregation - cloned interface"
  community.general.sysrc:
    name: "cloned_interfaces"
    value: "{{ main_trunk.interface }}"
    state: value_present
  notify:
    - "restart network"

- name: "Configure link aggregation - setup {{ main_trunk.interface }}"
  community.general.sysrc:
    name: "ifconfig_{{ main_trunk.interface }}"
    value: "create laggproto lacp laggport {{ main_trunk.members | join(' laggport ') }}"
  notify:
    - "restart network"

- include_tasks: vlan.yaml
  loop: "{{ main_trunk.vlans }}"
  loop_control:
    loop_var: vlan_dict

- name: "Configure dhcpcd"
  ansible.builtin.template:
    src: dhcpcd.conf.j2
    dest: /usr/local/etc/dhcpcd.conf
  notify:
    - "restart network"

- name: Flush handlers
  meta: flush_handlers
