---
- name: "Install prerequisites"
  community.general.pkgng:
    name:
      - doas
      - python
    state: present

- name: "Generate rc.conf"
  ansible.builtin.template:
    src: "rc.conf.j2"
    dest: "/etc/rc.conf"
